# Generated by Django 4.1.7 on 2023-05-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_costumer_address_alter_pemilikkos_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilikkos',
            name='no_rekening',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
