# Generated by Django 4.1.7 on 2023-05-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_poi_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='listing',
        ),
    ]
